scrape_interval = "10s"
mgrctl_path = "/home/kias/go/isp-site-checker/mgrctl-test"
recipient = "admin@example.ru"

[smtp]
    username = "admin@example.ru"
    password = "hello-world"
    host = "mail.example.ru"
    port = 465
    from = "admin@example.ru"