mgrctl_path = "path/to/mgrctl"

scrape_interval = "10s"
send_interval = "10s"

[smtp]
username = "user1"
password = "password"
host = "smtp.example.ru"
port = "587"

[email]
from = "Служба проверки доменов <user1@example.ru>"
to = ["receiver@www.example.ru"]
subject = "Test"